"""widen users.password_hash to 255

Revision ID: 0c0cbecb37b6
Revises: 0b2c091e10de
Create Date: 2025-10-19 01:24:05.600070

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c0cbecb37b6'
down_revision = '0b2c091e10de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('scan_results')
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_source'))
        batch_op.drop_index(batch_op.f('ix_report_url'))
        batch_op.drop_index(batch_op.f('ix_report_user_id'))

    op.drop_table('report')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=255),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=128),
               nullable=True)

    op.create_table('report',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('source', sa.VARCHAR(length=32), nullable=False),
    sa.Column('note', sa.VARCHAR(length=512), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=True),
    sa.Column('label', sa.VARCHAR(length=8), nullable=True),
    sa.Column('evaluated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_report_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_url'), ['url'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_source'), ['source'], unique=False)

    op.create_table('scan_results',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('url', sa.VARCHAR(length=2048), nullable=False),
    sa.Column('is_phishing', sa.BOOLEAN(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('email', sa.VARCHAR(length=255), nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=255), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('email_confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=1)

    # ### end Alembic commands ###
