"""Add scoring fields to Report (score/label/evaluated_at)

Revision ID: 8d896a4f6484
Revises: ff5d19d59050
Create Date: 2025-10-04 19:32:57.029772

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d896a4f6484'
down_revision = 'ff5d19d59050'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('score', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('label', sa.String(length=8), nullable=True))
        batch_op.add_column(sa.Column('evaluated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_report_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_report_url'), ['url'], unique=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('report', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_report_url'))
        batch_op.drop_index(batch_op.f('ix_report_source'))
        batch_op.drop_column('evaluated_at')
        batch_op.drop_column('label')
        batch_op.drop_column('score')

    # ### end Alembic commands ###
